apiVersion: alerts.k8s.newrelic.com/v1
kind: NrqlCondition
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: nrqlcondition-baseline-example
spec:
  accountId: 1
  apiKey: <api_key>
  # api_key_secret:
  #   name: nr-api-key
  #   namespace: default
  #   key_name: api-key
  region: "US"
  name: "Example Baseline Condition"
  description: "test description"
  # Must reference an existing New Relic alert policy from your account
  existingPolicyId: "123456"
  type: BASELINE
  nrql:
    query: "SELECT count(*) FROM Transactio22n"
  enabled: true
  runbookUrl: "https://www.google.com"
  terms:
    - threshold: "60"
      thresholdOccurrences: ALL
      thresholdDuration: 120
      priority: CRITICAL
      operator: ABOVE
  expiration:
    expirationDuration: 360
    closeViolationsOnExpiration: true
    openViolationOnExpiration: false
  signal:
    aggregationWindow: 60
    aggregationMethod: EVENT_TIMER
    #aggregationDelay: 60
    aggregationTimer: 60
  baselineDirection: "UPPER_ONLY" # UPPER_ONLY | LOWER_ONLY | UPPER_AND_LOWER
