//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/newrelic/newrelic-client-go/v2/pkg/alerts"
	"github.com/newrelic/newrelic-client-go/v2/pkg/notifications"
	"github.com/newrelic/newrelic-client-go/v2/pkg/workflows"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiNotificationsCredentialsInput) DeepCopyInto(out *AiNotificationsCredentialsInput) {
	*out = *in
	out.Basic = in.Basic
	if in.CustomHeaders != nil {
		in, out := &in.CustomHeaders, &out.CustomHeaders
		*out = new(AiNotificationsCustomHeadersAuthInput)
		(*in).DeepCopyInto(*out)
	}
	out.Oauth2 = in.Oauth2
	out.Token = in.Token
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiNotificationsCredentialsInput.
func (in *AiNotificationsCredentialsInput) DeepCopy() *AiNotificationsCredentialsInput {
	if in == nil {
		return nil
	}
	out := new(AiNotificationsCredentialsInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiNotificationsCustomHeadersAuthInput) DeepCopyInto(out *AiNotificationsCustomHeadersAuthInput) {
	*out = *in
	if in.CustomHeaders != nil {
		in, out := &in.CustomHeaders, &out.CustomHeaders
		*out = make([]notifications.AiNotificationsCustomHeaderInput, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiNotificationsCustomHeadersAuthInput.
func (in *AiNotificationsCustomHeadersAuthInput) DeepCopy() *AiNotificationsCustomHeadersAuthInput {
	if in == nil {
		return nil
	}
	out := new(AiNotificationsCustomHeadersAuthInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiNotificationsPropertyInput) DeepCopyInto(out *AiNotificationsPropertyInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiNotificationsPropertyInput.
func (in *AiNotificationsPropertyInput) DeepCopy() *AiNotificationsPropertyInput {
	if in == nil {
		return nil
	}
	out := new(AiNotificationsPropertyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiWorkflowsEnrichmentsInput) DeepCopyInto(out *AiWorkflowsEnrichmentsInput) {
	*out = *in
	if in.NRQL != nil {
		in, out := &in.NRQL, &out.NRQL
		*out = make([]AiWorkflowsNRQLEnrichmentInput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiWorkflowsEnrichmentsInput.
func (in *AiWorkflowsEnrichmentsInput) DeepCopy() *AiWorkflowsEnrichmentsInput {
	if in == nil {
		return nil
	}
	out := new(AiWorkflowsEnrichmentsInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiWorkflowsFilterInput) DeepCopyInto(out *AiWorkflowsFilterInput) {
	*out = *in
	if in.Predicates != nil {
		in, out := &in.Predicates, &out.Predicates
		*out = make([]AiWorkflowsPredicateInput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiWorkflowsFilterInput.
func (in *AiWorkflowsFilterInput) DeepCopy() *AiWorkflowsFilterInput {
	if in == nil {
		return nil
	}
	out := new(AiWorkflowsFilterInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiWorkflowsNRQLConfigurationInput) DeepCopyInto(out *AiWorkflowsNRQLConfigurationInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiWorkflowsNRQLConfigurationInput.
func (in *AiWorkflowsNRQLConfigurationInput) DeepCopy() *AiWorkflowsNRQLConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(AiWorkflowsNRQLConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiWorkflowsNRQLEnrichmentInput) DeepCopyInto(out *AiWorkflowsNRQLEnrichmentInput) {
	*out = *in
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = make([]AiWorkflowsNRQLConfigurationInput, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiWorkflowsNRQLEnrichmentInput.
func (in *AiWorkflowsNRQLEnrichmentInput) DeepCopy() *AiWorkflowsNRQLEnrichmentInput {
	if in == nil {
		return nil
	}
	out := new(AiWorkflowsNRQLEnrichmentInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AiWorkflowsPredicateInput) DeepCopyInto(out *AiWorkflowsPredicateInput) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AiWorkflowsPredicateInput.
func (in *AiWorkflowsPredicateInput) DeepCopy() *AiWorkflowsPredicateInput {
	if in == nil {
		return nil
	}
	out := new(AiWorkflowsPredicateInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannel) DeepCopyInto(out *AlertChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannel.
func (in *AlertChannel) DeepCopy() *AlertChannel {
	if in == nil {
		return nil
	}
	out := new(AlertChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelList) DeepCopyInto(out *AlertChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AlertChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelList.
func (in *AlertChannelList) DeepCopy() *AlertChannelList {
	if in == nil {
		return nil
	}
	out := new(AlertChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelSpec) DeepCopyInto(out *AlertChannelSpec) {
	*out = *in
	out.APIKeySecret = in.APIKeySecret
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]AiNotificationsPropertyInput, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelSpec.
func (in *AlertChannelSpec) DeepCopy() *AlertChannelSpec {
	if in == nil {
		return nil
	}
	out := new(AlertChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannelStatus) DeepCopyInto(out *AlertChannelStatus) {
	*out = *in
	if in.AppliedSpec != nil {
		in, out := &in.AppliedSpec, &out.AppliedSpec
		*out = new(AlertChannelSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannelStatus.
func (in *AlertChannelStatus) DeepCopy() *AlertChannelStatus {
	if in == nil {
		return nil
	}
	out := new(AlertChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertDestination) DeepCopyInto(out *AlertDestination) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertDestination.
func (in *AlertDestination) DeepCopy() *AlertDestination {
	if in == nil {
		return nil
	}
	out := new(AlertDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertDestination) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertDestinationBaseSpec) DeepCopyInto(out *AlertDestinationBaseSpec) {
	*out = *in
	out.APIKeySecret = in.APIKeySecret
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AiNotificationsCredentialsInput)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]AiNotificationsPropertyInput, len(*in))
		copy(*out, *in)
	}
	if in.SecureURL != nil {
		in, out := &in.SecureURL, &out.SecureURL
		*out = new(notifications.AiNotificationsSecureURLInput)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertDestinationBaseSpec.
func (in *AlertDestinationBaseSpec) DeepCopy() *AlertDestinationBaseSpec {
	if in == nil {
		return nil
	}
	out := new(AlertDestinationBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertDestinationList) DeepCopyInto(out *AlertDestinationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AlertDestination, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertDestinationList.
func (in *AlertDestinationList) DeepCopy() *AlertDestinationList {
	if in == nil {
		return nil
	}
	out := new(AlertDestinationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertDestinationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertDestinationSpec) DeepCopyInto(out *AlertDestinationSpec) {
	*out = *in
	in.AlertDestinationBaseSpec.DeepCopyInto(&out.AlertDestinationBaseSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertDestinationSpec.
func (in *AlertDestinationSpec) DeepCopy() *AlertDestinationSpec {
	if in == nil {
		return nil
	}
	out := new(AlertDestinationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertDestinationStatus) DeepCopyInto(out *AlertDestinationStatus) {
	*out = *in
	if in.AppliedSpec != nil {
		in, out := &in.AppliedSpec, &out.AppliedSpec
		*out = new(AlertDestinationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertDestinationStatus.
func (in *AlertDestinationStatus) DeepCopy() *AlertDestinationStatus {
	if in == nil {
		return nil
	}
	out := new(AlertDestinationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertPolicy) DeepCopyInto(out *AlertPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertPolicy.
func (in *AlertPolicy) DeepCopy() *AlertPolicy {
	if in == nil {
		return nil
	}
	out := new(AlertPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertPolicyList) DeepCopyInto(out *AlertPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AlertPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertPolicyList.
func (in *AlertPolicyList) DeepCopy() *AlertPolicyList {
	if in == nil {
		return nil
	}
	out := new(AlertPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertPolicySpec) DeepCopyInto(out *AlertPolicySpec) {
	*out = *in
	out.APIKeySecret = in.APIKeySecret
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]PolicyCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertPolicySpec.
func (in *AlertPolicySpec) DeepCopy() *AlertPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AlertPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertPolicyStatus) DeepCopyInto(out *AlertPolicyStatus) {
	*out = *in
	if in.AppliedSpec != nil {
		in, out := &in.AppliedSpec, &out.AppliedSpec
		*out = new(AlertPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertPolicyStatus.
func (in *AlertPolicyStatus) DeepCopy() *AlertPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AlertPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertWorkflow) DeepCopyInto(out *AlertWorkflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertWorkflow.
func (in *AlertWorkflow) DeepCopy() *AlertWorkflow {
	if in == nil {
		return nil
	}
	out := new(AlertWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertWorkflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertWorkflowList) DeepCopyInto(out *AlertWorkflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AlertWorkflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertWorkflowList.
func (in *AlertWorkflowList) DeepCopy() *AlertWorkflowList {
	if in == nil {
		return nil
	}
	out := new(AlertWorkflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertWorkflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertWorkflowSpec) DeepCopyInto(out *AlertWorkflowSpec) {
	*out = *in
	out.APIKeySecret = in.APIKeySecret
	if in.IssuesFilter != nil {
		in, out := &in.IssuesFilter, &out.IssuesFilter
		*out = new(AiWorkflowsFilterInput)
		(*in).DeepCopyInto(*out)
	}
	in.Enrichments.DeepCopyInto(&out.Enrichments)
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]DestinationChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertWorkflowSpec.
func (in *AlertWorkflowSpec) DeepCopy() *AlertWorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(AlertWorkflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertWorkflowStatus) DeepCopyInto(out *AlertWorkflowStatus) {
	*out = *in
	if in.AppliedSpec != nil {
		in, out := &in.AppliedSpec, &out.AppliedSpec
		*out = new(AlertWorkflowSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertWorkflowStatus.
func (in *AlertWorkflowStatus) DeepCopy() *AlertWorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(AlertWorkflowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsBaselineSpecificSpec) DeepCopyInto(out *AlertsBaselineSpecificSpec) {
	*out = *in
	if in.BaselineDirection != nil {
		in, out := &in.BaselineDirection, &out.BaselineDirection
		*out = new(alerts.NrqlBaselineDirection)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsBaselineSpecificSpec.
func (in *AlertsBaselineSpecificSpec) DeepCopy() *AlertsBaselineSpecificSpec {
	if in == nil {
		return nil
	}
	out := new(AlertsBaselineSpecificSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsNrqlBaseSpec) DeepCopyInto(out *AlertsNrqlBaseSpec) {
	*out = *in
	out.APIKeySecret = in.APIKeySecret
	in.Nrql.DeepCopyInto(&out.Nrql)
	if in.Terms != nil {
		in, out := &in.Terms, &out.Terms
		*out = make([]AlertsNrqlConditionTerm, len(*in))
		copy(*out, *in)
	}
	if in.Expiration != nil {
		in, out := &in.Expiration, &out.Expiration
		*out = new(AlertsNrqlConditionExpiration)
		(*in).DeepCopyInto(*out)
	}
	if in.Signal != nil {
		in, out := &in.Signal, &out.Signal
		*out = new(AlertsNrqlConditionSignal)
		(*in).DeepCopyInto(*out)
	}
	if in.TitleTemplate != nil {
		in, out := &in.TitleTemplate, &out.TitleTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsNrqlBaseSpec.
func (in *AlertsNrqlBaseSpec) DeepCopy() *AlertsNrqlBaseSpec {
	if in == nil {
		return nil
	}
	out := new(AlertsNrqlBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsNrqlConditionExpiration) DeepCopyInto(out *AlertsNrqlConditionExpiration) {
	*out = *in
	if in.ExpirationDuration != nil {
		in, out := &in.ExpirationDuration, &out.ExpirationDuration
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsNrqlConditionExpiration.
func (in *AlertsNrqlConditionExpiration) DeepCopy() *AlertsNrqlConditionExpiration {
	if in == nil {
		return nil
	}
	out := new(AlertsNrqlConditionExpiration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsNrqlConditionSignal) DeepCopyInto(out *AlertsNrqlConditionSignal) {
	*out = *in
	if in.AggregationWindow != nil {
		in, out := &in.AggregationWindow, &out.AggregationWindow
		*out = new(int)
		**out = **in
	}
	if in.EvaluationOffset != nil {
		in, out := &in.EvaluationOffset, &out.EvaluationOffset
		*out = new(int)
		**out = **in
	}
	if in.EvaluationDelay != nil {
		in, out := &in.EvaluationDelay, &out.EvaluationDelay
		*out = new(int)
		**out = **in
	}
	if in.FillOption != nil {
		in, out := &in.FillOption, &out.FillOption
		*out = new(alerts.AlertsFillOption)
		**out = **in
	}
	if in.FillValue != nil {
		in, out := &in.FillValue, &out.FillValue
		*out = new(float64)
		**out = **in
	}
	if in.AggregationMethod != nil {
		in, out := &in.AggregationMethod, &out.AggregationMethod
		*out = new(alerts.NrqlConditionAggregationMethod)
		**out = **in
	}
	if in.AggregationDelay != nil {
		in, out := &in.AggregationDelay, &out.AggregationDelay
		*out = new(int)
		**out = **in
	}
	if in.AggregationTimer != nil {
		in, out := &in.AggregationTimer, &out.AggregationTimer
		*out = new(int)
		**out = **in
	}
	if in.SlideBy != nil {
		in, out := &in.SlideBy, &out.SlideBy
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsNrqlConditionSignal.
func (in *AlertsNrqlConditionSignal) DeepCopy() *AlertsNrqlConditionSignal {
	if in == nil {
		return nil
	}
	out := new(AlertsNrqlConditionSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsNrqlConditionTerm) DeepCopyInto(out *AlertsNrqlConditionTerm) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsNrqlConditionTerm.
func (in *AlertsNrqlConditionTerm) DeepCopy() *AlertsNrqlConditionTerm {
	if in == nil {
		return nil
	}
	out := new(AlertsNrqlConditionTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationChannel) DeepCopyInto(out *DestinationChannel) {
	*out = *in
	if in.NotificationTriggers != nil {
		in, out := &in.NotificationTriggers, &out.NotificationTriggers
		*out = make([]workflows.AiWorkflowsNotificationTrigger, len(*in))
		copy(*out, *in)
	}
	if in.UpdateOriginalMessage != nil {
		in, out := &in.UpdateOriginalMessage, &out.UpdateOriginalMessage
		*out = new(bool)
		**out = **in
	}
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationChannel.
func (in *DestinationChannel) DeepCopy() *DestinationChannel {
	if in == nil {
		return nil
	}
	out := new(DestinationChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationChannelSpec) DeepCopyInto(out *DestinationChannelSpec) {
	*out = *in
	in.AlertChannelSpec.DeepCopyInto(&out.AlertChannelSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationChannelSpec.
func (in *DestinationChannelSpec) DeepCopy() *DestinationChannelSpec {
	if in == nil {
		return nil
	}
	out := new(DestinationChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityTag) DeepCopyInto(out *EntityTag) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityTag.
func (in *EntityTag) DeepCopy() *EntityTag {
	if in == nil {
		return nil
	}
	out := new(EntityTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityTagging) DeepCopyInto(out *EntityTagging) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityTagging.
func (in *EntityTagging) DeepCopy() *EntityTagging {
	if in == nil {
		return nil
	}
	out := new(EntityTagging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EntityTagging) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityTaggingList) DeepCopyInto(out *EntityTaggingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EntityTagging, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityTaggingList.
func (in *EntityTaggingList) DeepCopy() *EntityTaggingList {
	if in == nil {
		return nil
	}
	out := new(EntityTaggingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EntityTaggingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityTaggingSpec) DeepCopyInto(out *EntityTaggingSpec) {
	*out = *in
	in.TagBaseSpec.DeepCopyInto(&out.TagBaseSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityTaggingSpec.
func (in *EntityTaggingSpec) DeepCopy() *EntityTaggingSpec {
	if in == nil {
		return nil
	}
	out := new(EntityTaggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityTaggingStatus) DeepCopyInto(out *EntityTaggingStatus) {
	*out = *in
	if in.AppliedSpec != nil {
		in, out := &in.AppliedSpec, &out.AppliedSpec
		*out = new(EntityTaggingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ManagedEntities != nil {
		in, out := &in.ManagedEntities, &out.ManagedEntities
		*out = make([]ManagedEntity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityTaggingStatus.
func (in *EntityTaggingStatus) DeepCopy() *EntityTaggingStatus {
	if in == nil {
		return nil
	}
	out := new(EntityTaggingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedEntity) DeepCopyInto(out *ManagedEntity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedEntity.
func (in *ManagedEntity) DeepCopy() *ManagedEntity {
	if in == nil {
		return nil
	}
	out := new(ManagedEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewRelicSecret) DeepCopyInto(out *NewRelicSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewRelicSecret.
func (in *NewRelicSecret) DeepCopy() *NewRelicSecret {
	if in == nil {
		return nil
	}
	out := new(NewRelicSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlCondition) DeepCopyInto(out *NrqlCondition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlCondition.
func (in *NrqlCondition) DeepCopy() *NrqlCondition {
	if in == nil {
		return nil
	}
	out := new(NrqlCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NrqlCondition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlConditionCreateQuery) DeepCopyInto(out *NrqlConditionCreateQuery) {
	*out = *in
	if in.DataAccountID != nil {
		in, out := &in.DataAccountID, &out.DataAccountID
		*out = new(int)
		**out = **in
	}
	if in.EvaluationOffset != nil {
		in, out := &in.EvaluationOffset, &out.EvaluationOffset
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlConditionCreateQuery.
func (in *NrqlConditionCreateQuery) DeepCopy() *NrqlConditionCreateQuery {
	if in == nil {
		return nil
	}
	out := new(NrqlConditionCreateQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlConditionList) DeepCopyInto(out *NrqlConditionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NrqlCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlConditionList.
func (in *NrqlConditionList) DeepCopy() *NrqlConditionList {
	if in == nil {
		return nil
	}
	out := new(NrqlConditionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NrqlConditionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlConditionSpec) DeepCopyInto(out *NrqlConditionSpec) {
	*out = *in
	in.AlertsNrqlBaseSpec.DeepCopyInto(&out.AlertsNrqlBaseSpec)
	in.AlertsBaselineSpecificSpec.DeepCopyInto(&out.AlertsBaselineSpecificSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlConditionSpec.
func (in *NrqlConditionSpec) DeepCopy() *NrqlConditionSpec {
	if in == nil {
		return nil
	}
	out := new(NrqlConditionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrqlConditionStatus) DeepCopyInto(out *NrqlConditionStatus) {
	*out = *in
	if in.AppliedSpec != nil {
		in, out := &in.AppliedSpec, &out.AppliedSpec
		*out = new(NrqlConditionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrqlConditionStatus.
func (in *NrqlConditionStatus) DeepCopy() *NrqlConditionStatus {
	if in == nil {
		return nil
	}
	out := new(NrqlConditionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCondition) DeepCopyInto(out *PolicyCondition) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCondition.
func (in *PolicyCondition) DeepCopy() *PolicyCondition {
	if in == nil {
		return nil
	}
	out := new(PolicyCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyConditionSpec) DeepCopyInto(out *PolicyConditionSpec) {
	*out = *in
	in.NrqlConditionSpec.DeepCopyInto(&out.NrqlConditionSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyConditionSpec.
func (in *PolicyConditionSpec) DeepCopy() *PolicyConditionSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyConditionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagBaseSpec) DeepCopyInto(out *TagBaseSpec) {
	*out = *in
	out.APIKeySecret = in.APIKeySecret
	if in.EntityNames != nil {
		in, out := &in.EntityNames, &out.EntityNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*EntityTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(EntityTag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagBaseSpec.
func (in *TagBaseSpec) DeepCopy() *TagBaseSpec {
	if in == nil {
		return nil
	}
	out := new(TagBaseSpec)
	in.DeepCopyInto(out)
	return out
}
