apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-alertpolicy-viewer-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - alerts.k8s.newrelic.com
  resources:
  - alertpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alerts.k8s.newrelic.com
  resources:
  - alertpolicies/status
  verbs:
  - get