apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        {{- include "chart.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- tpl (.Values.controllerManager.annotations | toYaml) . | nindent 8 }}
    spec:
      securityContext: {{- toYaml .Values.controllerManager.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.controllerManager.manager.image.pullPolicy }}
          command:
            - /manager
          args: {{- toYaml .Values.controllerManager.manager.args | nindent 12 }}
          env:
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 12 }}
          securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext | nindent 12 }}
      affinity: {{- toYaml .Values.controllerManager.affinity | nindent 8 }}
      tolerations: {{- toYaml .Values.controllerManager.tolerations | nindent 8 }}
      nodeSelector: {{- toYaml .Values.controllerManager.nodeSelector | nindent 8 }}
