{{- if .Values.controllerManager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" . }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- tpl (toYaml .Values.controllerManager.serviceAccount.annotations) . | nindent 4 }}
{{- end }}