---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alerts.k8s.newrelic.com
  resources:
  - alertchannels
  - alertdestinations
  - alertpolicies
  - alertworkflows
  - nrqlconditions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alerts.k8s.newrelic.com
  resources:
  - alertchannels/finalizers
  - alertdestinations/finalizers
  - alertpolicies/finalizers
  - alertworkflows/finalizers
  - nrqlconditions/finalizers
  verbs:
  - update
- apiGroups:
  - alerts.k8s.newrelic.com
  resources:
  - alertchannels/status
  - alertpolicies/status
  - alertworkflows/status
  - nrqlconditions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - alerts.k8s.newrelic.com
  resources:
  - alertdestinations/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
