apiVersion: alerts.k8s.newrelic.com/v1
kind: EntityTagging
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: entity-tag-example
spec:
  apiKey: <api_key>
  # api_key_secret:
  #   name: nr-api-key
  #   namespace: default
  #   key_name: api-key
  region: "US"
  entityNames: # Required - list of existing entity names to apply tags to
    - Entity1
    - Entity2
  tags: # Required - list of key-values pairs to apply to entities listed
    - key: tag1
      values:
        - value1
    - key: tag2
      values:
        - value123
        - value456