controllerManager:
  replicas: 1
  serviceAccount:
    create: false
    annotations: {}
  podSecurityContext:
    runAsNonRoot: true
  manager:
    args:
      - --metrics-bind-address=:8443
      - --leader-elect
      - --health-probe-bind-address=:8081
    image:
      repository: newrelic/newrelic-k8s-operator-v2
      tag: latest
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  affinity: {}
  tolerations: {}
  nodeSelector: {}

kubernetesClusterDomain: cluster.local

metricsService:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
