apiVersion: alerts.k8s.newrelic.com/v1
kind: AlertPolicy
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: alertpolicy-example
spec:
  # TODO(user): Add fields here
  apiKey: <api_key>
  # apiKeySecret:
  #   name: nr-api-key
  #   namespace: default
  #   keyName: api-key
  accountId: 1
  region: "US"
  name: Test-Policy-K8s
  incidentPreference: PER_CONDITION
