apiVersion: alerts.k8s.newrelic.com/v1
kind: AlertChannel
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: alertchannel-email-example
spec:
  accountId: 1
  apiKey: <api_key>
  region: "US"
  name: "test-email-channel"
  destinationName: "<destination_name>"
  product: "IINT"
  properties:
    - key: "subject"
      value: "Example Email Subject"
    - key: "customDetailsEmail"
      value: "issue id - {{issueId}}"
  type: "EMAIL"
