apiVersion: alerts.k8s.newrelic.com/v1
kind: AlertChannel
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: alertchannel-webhook-example
spec:
  accountId: 1
  apiKey: <api_key>
  region: "US"
  name: "test-webhook-channel"
  destinationId: "<destination_id>"
  product: "IINT"
  properties:
    - key: "payload"
      label: "Payload Template"
      value: '{
            "id":{{json issueId}},
            "IssueURL":{{json issuePageUrl}}
            }'
  type: "WEBHOOK"
