apiVersion: alerts.k8s.newrelic.com/v1
kind: AlertChannel
metadata:
  labels:
    app.kubernetes.io/name: newrelic-kubernetes-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: alertchannel-slack-example
spec:
  accountId: 1
  apiKey: <api_key>
  region: "US"
  name: "test-slack-channel"
  destinationName: "<destination_name>"
  product: "IINT"
  properties:
    - key: "channelId"
      value: "123456"
    - key: "customDetailsSlack"
      value: "issue id - {{issueId}}"
  type: "SLACK"
